### ISSUE TITLE
Multiple thingClass errors and discussion on patches for Zen Garden & Bonsaiplus

### ISSUE THREAD

**Issue by Luinithil** [Adventurer13/ExpandedWoodworkingVGP#2]
Getting error spam from the above, also suspect it might be making **Prepare Carefully** wig out over inability to calculate item values for starting points. Note that I will be moving Stuffed Floors after EWVG after this, per your advice.

**Link to output log**: https://gist.github.com/HugsLibRecordKeeper/76c13efe8a67687a443d438df785ac23
**Modlist (very long)**: 
[modlist.txt](https://github.com/Adventurer13/ExpandedWoodworkingVG/files/1202536/modlist.txt)

**Comment by Adventurer13** [comment]
Wow, you use a lot of mods! I use over 100 regularly and haven't reached 200 yet.

I think I have fixed the problem with Prepare Carefully and it's points system (the null thing class errors regarding torches, horseshoes pins, and passive coolers). The fix will be in the next update.

I have heard of most of the mods you use, however, I do not use a good portion and would like to avoid downloading all of them. You mentioned on the mod page that fully grown trees were not producing logs, correct? To possibly narrow down what is causing the incompatibility, was this specific to only trees added by Vegetable Garden or vanilla trees as well?

**Comment by Luinithil** [comment]
Hey, FYI, my current mod order's attached below-- I've been testing with this.

I haven't had time to playtest further, but as far as I can see, it's specifically the cherry and Japanese maple trees (I think the Japanese maples at least are not from VG or your mod) that have this issue. 

Right now with current mod order, when I find a cherry tree in the wild on the map, it's a very pretty pink tree -- chopping it down at full maturity I get cherry *wood* and not logs! Dev tools _place direct thing_ option shows me two different objects, both called "cherry tree"-- one is the pink blossomed tree, another is a tree with VG graphics (red cherries). The tree with VG graphics behaves as expected with this mod and drops cherrywood logs.

All other trees added by VG (and vanilla AFAIK) are behaving as expected. 

So it looks like there's conflicts with VG vs Cupro's Zen Garden vs bonsaiplus and this mod-- All of them modify Japanese maples, cherry trees and/or Japanese cherry trees and cherry blossom trees (I clearly have too many modded tree types now), which is where the vanishing logs and unexpected wood come from; same names, and maybe modifying the same things, but I'll see if I can't narrow it down more.


[modlist.txt](https://github.com/Adventurer13/ExpandedWoodworkingVG/files/1218505/modlist.txt)

**Comment by Adventurer13** [comment]
Okay, so I took a look into the assembly and definitions for Zen Garden and Bonsaiplus (of which Bonsaiplus does not have an assembly, only definitions). I haven't used either of them, but I do know of them.

Zen Garden produces it's own _cherry wood_ as you noted. I could potentially create a patch system in Expanded Woodworking to change the label into logs and a notifier that it is Zen Garden's for the both the resource and the tree. This would allow for differentiation within the dev tools as well as the resource produced while maintaining the production chain of logs into lumber that Expanded Woodworking introduces. However, this won't allow for logs being produced while harvesting the cherries. This would be the simple fix (and the quickest for me to implement) if you do not mind having to cut down the tree in order to receive the logs. The other and longer to implement option is for me to add the system similar to this VG add-on where harvesting also produces logs. This would require a separate mod like VG does. Do you have a preference for the simple patch or a separate mod?

It appears that bonsaiplus just produces wood like vanilla. Is this the case in-game or is it producing mixed lumber outright with harvesting? Or something else entirely?

Neither of these affect this mod or VG since their definition names are different and independent for each type of tree. Their label names are very similar, which is what I think you are referring to. Zen Garden introduces another Cherry tree. Bonsaiplus introduces bonsai versions of the vanilla trees (pine, oak, poplar, birch, teak, cecropia) and cacti (saguaro) as well as another pine (matsu), cherry blossom (sakura), plum (ume), and maple (momiji). Are these what you are referring to?

**Comment by Luinithil** [comment]
I don't mind a separate patch mod, since harvesting a tree to produce wood sounds fairly realistic to me. However if you haven't the time to devote to this, the simple patch is more than fine. :)

I think I was trying to harvest a momiji, and that-- gave me nothing on harvesting (chopping down the tree). I'll have to try it again.

**Comment by Adventurer13** [comment]
I'll put this down as something to work on and plan to add. I'll take another look at Bonsaiplus again as well.

I have marked these as plans over on the [Expanded Woodworking repository](https://github.com/Adventurer13/ExpandedWoodworking/issues)

Also, regrading the nature of the title of this issue, are the thingClass errors (for torches, horseshoes pins, and passive coolers) fixed for you?

**Comment by Luinithil** [comment]
Thanks @Adventurer13 ! I'm assuming you updated the Steam version with the thingClass fix on the 9th, yeah? I can confirm that the thingClass errors aren't showing up in debug anymore.

**Comment by Adventurer13** [comment]
Yes. Thank you for letting me know.

**Comment by Adventurer13** [comment]
@Luinithil Zen Garden patch added [here on Github](https://github.com/Adventurer13/ExpandedWoodworking/releases/tag/v0.17.0.5) and Steam
